name: Build Java Application - Development

on:
  repository_dispatch:
    types: [dev]
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Java Code
        uses: actions/checkout@v2
        with:
          repository: atdevsecops/pocjavaproject
          ref: develop
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn -B package
