name: Build Java Application - Development

on:
  repository_dispatch:
    types: [dev]
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Java Code
        uses: actions/checkout@v2
        with:
          repository: atdevsecops/pocjavaproject
          ref: develop
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.2

      - name: Build with Maven
        run: mvn -B package

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.1.3
        with:
          version: '2.59.1'

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          jfrog rt config --url=$JFROG_URL --user=$JFROG_USER --password=$JFROG_PASSWORD

      - name: Upload to Artifactory
        run: jfrog rt u "target/*.jar" "APPS/Java/artifact/"
